version: "3.7"

services:
  web:
    image: linuxserver/nginx
    container_name: web-container
    ports:
      - "8080:80"
    environment:
      - PHP_FPM_ENABLE=true
      - PHP_FPM_HOST=127.0.0.1
      - PHP_FPM_PORT=9000
    volumes:
      - ./index.php:/config/www/index.php
    networks:
      - web-network

  db:
    image: mariadb:latest
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - ./InitDB.sql:/docker-entrypoint-initdb.d/InitDB.sql
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
