version: "3.7"

services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: web-container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./index.php:/config/www/index.php
    ports:
      - 80:80
      - 443:443
    networks:
      - web-network

  db:
    image: mariadb:latest
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - ./InitDB.sql:/docker-entrypoint-initdb.d/InitDB.sql
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
